services:
  api:
    build: .
    container_name: mock_api_node
    env_file:
      - .env
    ports:
      - "8282:8282"
    volumes:
      - ./server.js:/app/server.js
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mock_api_mongo
    ports:
      - "59213:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
