services:
  api:
    build: .
    container_name: mock_api_node
    env_file:
      - .env
    ports:
      - "8282:8282"
    volumes:
      - ./server.js:/app/server.js
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mock_api_mongo
    ports:
      - "59213:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    container_name: mock_api_ngrok
    env_file:
      - .env
    command:
      - "http"
      - "--domain=${NGROK_DOMAIN}"
      - "api:${PORT}"
    ports:
      - 4040:4040
    depends_on:
      - api

volumes:
  mongo_data:
